name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main  # Chạy khi có thay đổi trên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: frontend  # Đường dẫn đến thư mục frontend
        
      - name: Check installed dependencies
        run: npm list
        working-directory: frontend

      - name: Build project
        run: CI=false npm run build
        working-directory: frontend

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: 54.215.38.215   # Địa chỉ IP của EC2
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/build/*"
          target: "/home/ec2-user/build"

      - name: Restart Web Server
        uses: appleboy/ssh-action@master
        with:
          host: 54.215.38.215
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart nginx
