name: Deploy Fullstack to EC2

on:
  push:
    branches:
      - main  # Mỗi khi push lên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Copy FRONTEND source code lên EC2
      - name: Copy FRONTEND source code to EC2
        uses: appleboy/scp-action@master
        with:
          host: 13.57.34.159
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/"
          target: "/home/ec2-user/"

      # 3. Copy BACKEND source code lên EC2
      - name: Copy BACKEND source code to EC2
        uses: appleboy/scp-action@master
        with:
          host: 13.57.34.159
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend/"
          target: "/home/ec2-user/"

      # 4. Cài Node.js trên EC2 (nếu chưa cài)
      - name: Install Node.js & npm on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.57.34.159
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Cài Node.js 18.x
            curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
            sudo yum install -y nodejs
            node -v
            npm -v

      # 5. Build FRONTEND trên EC2
      - name: Build frontend on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.57.34.159
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # timeout: 1800
          script: |
            cd /home/ec2-user/frontend
            npm install
            npm run build
            ls -lah build/

      # 6. Deploy FRONTEND build sang /var/www/html (hoặc folder tuỳ ý)
      # - name: Deploy build to Apache
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       sudo rm -rf /var/www/html/*
      #       sudo cp -r /home/ec2-user/frontend/build/* /var/www/html/
      #       sudo chown -R apache:apache /var/www/html
      #       sudo chmod -R 755 /var/www/html
      #       sudo systemctl restart httpd
      - name: Deploy build to Nginx
        uses: appleboy/ssh-action@master
        with:
          host: 13.57.34.159
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r /home/ec2-user/frontend/build/* /usr/share/nginx/html/
            sudo chown -R nginx:nginx /usr/share/nginx/html
            sudo chmod -R 755 /usr/share/nginx/html
            sudo systemctl restart nginx
    
      # 7. Cài đặt Backend dependencies & run
      - name: Deploy backend on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.57.34.159
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/backend
            npm install

            # Bạn có thể build nếu có step build (TypeScript, Babel, v.v.), ví dụ:
            # npm run build

            # Dùng pm2 để chạy server (đảm bảo pm2 đã được cài)
            sudo npm install -g pm2
            pm2 stop my-backend || true
            pm2 delete my-backend || true
            pm2 start ./src/app.js --name my-backend --watch

            # Kiểm tra pm2 status
            pm2 status
