name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main  # Chạy khi có thay đổi trên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd frontend
          docker build -t myapp-frontend:latest .

      # - name: Save Docker image
      #   run: docker save -o frontend.tar myapp-frontend:latest
      - name: Save Docker image
        run: |
            docker save myapp-frontend:latest > frontend.tar
            ls -lh frontend.tar  # Kiểm tra dung lượng file
            file frontend.tar    # Kiểm tra loại file

      # Kiểm tra file frontend.tar có hợp lệ không
      - name: Debug permissions
        run: ls -lah frontend.tar

      - name: Verify Docker image exists
        run: ls -lh frontend.tar

      # Đảm bảo frontend.tar có quyền đúng trước khi copy
      - name: Fix permissions before SCP
        run: chmod 755 frontend.tar

      # Xóa file frontend.tar cũ trên EC2 trước khi copy
      - name: Cleanup old Docker image on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 54.215.38.215
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
              sudo rm -rf /home/ec2-user/frontend.tar


      # Copy Docker image lên EC2
      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@master
        with:
          host: 54.215.38.215
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend.tar"
          target: "/home/ec2-user/"
      - name: Verify frontend.tar on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 54.215.38.215
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls -lh /home/ec2-user/frontend.tar
            file /home/ec2-user/frontend.tar

      # Cấp quyền truy cập file frontend.tar cho Docker trên EC2
      - name: Auto Fix Permissions on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 54.215.38.215
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo chown ec2-user:ec2-user /home/ec2-user/frontend.tar
            sudo chmod 755 /home/ec2-user/frontend.tar  # Phân quyền đúng

      # Kiểm tra xem file frontend.tar có tồn tại trên EC2 hay không
      - name: Verify frontend.tar on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 54.215.38.215
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls -lh /home/ec2-user/frontend.tar
            file /home/ec2-user/frontend.tar

      # Load và chạy container trên EC2
      - name: Load and run Docker container on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 54.215.38.215
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker load -i /home/ec2-user/frontend.tar
            docker stop frontend || true
            docker rm frontend || true
            docker run -d -p 3000:3000 --name frontend myapp-frontend:latest
