name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main  # Chạy khi có thay đổi trên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd frontend
          docker build -t myapp-frontend:latest .

      - name: Save Docker image
        run: docker save -o frontend.tar myapp-frontend:latest

        #Kiểm tra file frontend.tar có hợp lí không
      - name: Debug permissions
        run: ls -lah frontend.tar

      - name: Verify Docker image exists
        run: ls -lh frontend.tar

        #Sửa quyền của frontend.tar
      - name: Fix permissions
        run: sudo chmod 644 frontend.tar
      - name: Cleanup old Docker image on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 54.215.38.215
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ -f "/home/ec2-user/frontend.tar" ]; then
              sudo rm -f /home/ec2-user/frontend.tar
            fi
      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@master
        with:
          host: 54.215.38.215   # Địa chỉ IP của EC2
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend.tar"
          target: "/home/ec2-user/frontend.tar"

      # - name: Fix permissions on EC2
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: 54.215.38.215
      #     username: ec2-user
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       sudo chmod 644 /home/ec2-user/frontend.tar
      - name: Fix permissions on EC2
        uses: appleboy/ssh-action@master
        with:
         host: 54.215.38.215
         username: ec2-user
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: |
           sudo chown ec2-user:ec2-user /home/ec2-user/frontend.tar
           sudo chmod 644 /home/ec2-user/frontend.tar
    
      - name: Load and run Docker container on EC2
        uses: appleboy/ssh-action@master
        with:
          host: 54.215.38.215
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker load < /home/ec2-user/frontend.tar
            docker stop frontend || true
            docker rm frontend || true
            docker run -d -p 3000:3000 --name frontend myapp-frontend:latest
